language: c
dist: trusty
compiler:
        - gcc
os:
        - linux
addons:
        sonarcloud:
                organization: "maelask3-github"
                token:
                        secure: "jdQWLFLWO53YATYKIihsgMGDbJrJ993K6rKQ4rP3wmfDmZ2swMAqU67TIvdpYSCdRMtHY/bMJ2kkTAOE5JI++iByTcRLWjZ7mQIJQfAqEWmXSowqedP5bMwhgkN7iDdXaslDY0IR8t4an/AIcTPAbQDczW25lBAj9bfngR84E1sizOVR/7UdZzLyqgBVZb4PCRIgV3Ec0y0IKHMjvL2cUhk/eYCggv2Wjb8tQInuCt8oaM2oS56z63f66z8+/fNURH5birIhRl1OMfsAiYz9AOp05cKe7Mxev5MVqdqhgBYCi9Pd2W337SZVZK7KOvA9kYYWSgvYrdV+BFR7REnabMFRBeTvaIg2wK6WtjvHJVB8KqVTMV+FP6x0st8PwycBFU3ck+yRnWEsfdPOHjK1s8PohOScUVNl0w+LCTKFejPUZ7pF2/K3d6xjv9uK41LsIgG5bbUVDvd+Am/r7rmO7IoiDtARveVWOqTb0y7BeTRlbmBhUSME2gqKug51aqzpjn3yYKh75hx77xBjwIPkBdwkmH+Ys0qjNaCzk2ZYIlkvo+bolcCKBytc7crOTxdV/AJ7RTrl16fLs9tQYs4guJ4rS5CFxWJEaO63P7FTrCnFryczIdzUNK9tS2f1fTVmcgdlJx7bbvPyuQdqi/UIkedJ5ns9tsb/rKJycw6lwe8="


script:
        - cmake . 
        - build-wrapper-linux-x86-64 --outdir bw-output make
        - sonar-scanner
        - ./POrbitD
